-- Payment gateway integration: drop unused balance column, relax fields that
-- aren't known until the gateway webhook fires, add gateway correlation id,
-- and fix the status enum (add Failed, drop unused In Progress).
--
-- NOTE: hand-written, not generated by `drizzle-kit generate` (no DB
-- connection available in this environment). Run `pnpm generate` against
-- your real database and diff against this file before applying.

ALTER TABLE "payment" DROP COLUMN "balance";--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "transaction_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_date" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_method" SET DEFAULT 'M-Pesa';--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_create" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "payment" ADD COLUMN "gateway_reference" varchar(100);--> statement-breakpoint

-- Postgres enums can't have a value removed directly — rebuild the enum.
ALTER TYPE "Paymentstatus" RENAME TO "Paymentstatus_old";--> statement-breakpoint
CREATE TYPE "Paymentstatus" AS ENUM ('Pending', 'Completed', 'Failed');--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "status" TYPE "Paymentstatus" USING (
  CASE "status"::text
    WHEN 'In Progress' THEN 'Pending'
    ELSE "status"::text
  END
)::"Paymentstatus";--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "status" SET DEFAULT 'Pending';--> statement-breakpoint
DROP TYPE "Paymentstatus_old";
