import cloudinary from "../../lib/cloudinary";

export const uploadImageService = (
  buffer: Buffer,
  folder: "profile" | "venue" | "event"
): Promise<string> => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        folder: `eventor/${folder}`,
        // UUID-style public_id generated by Cloudinary itself — never
        // trust a client-supplied filename.
        resource_type: "image",
      },
      (error, result) => {
        if (error || !result) {
          return reject(error ?? new Error("Cloudinary upload failed"));
        }
        resolve(result.secure_url);
      }
    );
    stream.end(buffer);
  });
};
